name: Unit Test
on:
  push:
    branches: [ "*" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux-amd64-fmt
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Unit test
        run: go test -gcflags=all=-l -coverprofile=cover.out ./...